language: 
  - java
jdk: 
  - oraclejdk8
  - oraclejdk7
before_install: 
  - sudo apt-get install libaudit-dev auditd libfuse-dev fuse
script: 
  - ./configure;
  - make
after_success:
  - make install
notifications:
  email:
    - hasanatkazmi@gmail.com
    - hassaan.irshad@sri.com
